config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products, except: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :sales
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :products
    has_many :ware_houses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
    belongs_to :supplier
    belongs_to :product
end
class ProductosController < ApplicationController
  before_action :current_producto, only: [:show, :edit, :update, :destroy]

  def index 
    @productos = Producto.all
  end 

  def show 
  end 

  #crear 
  def new 
    @producto = Producto.new 
  end 

  def create 
    @producto = Producto.create(producto_params)
    redirect_to productos_path
  end 

  #editar 
  def edit 
  end 

  def update 
    @producto.update(producto_params)
    redirect_to productos_path
  end 

  #eliminar
  def destroy 
    @producto.destroy
    redirect_to productos_path
  end


  private 
    def producto_params
        params.require(:producto).permit(:nombre, :descripcion, :marca, :modelo, :categoria, :color, :precio)      
    end

    def current_producto
        @producto = Producto.find(params[:id])
    end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "devise"
    else 
      "application"
    end 
  end         
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index 
    @categorias = Category.paginate(page: params[:page], per_page: 5)
  end 

  #crear 
  def new 
    @categoria = Category.new 
  end 

  def create 
    @categoria = Category.create(category_params)
    redirect_to categories_path
  end 

  #editar 
  def edit 
  end 

  def update 
    @categoria.update(category_params)
    redirect_to categories_path
  end 

  #eliminar
  def destroy 
    @categoria.destroy
    redirect_to categories_path
  end


  private 
    def category_params
        params.require(:category).permit(:nombre, :descripcion)      
    end

    def set_category
        @categoria = Category.find(params[:id])
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController 
  before_action :set_client, only: [:edit, :update, :destroy]

  def index 
    @clientes = Client.all
  end 

  #crear 
  def new 
    @cliente = Client.new 
  end 

  def create 
    @cliente = Client.create(client_params)
    redirect_to clients_path
  end 

  #editar 
  def edit 
  end 

  def update 
    @cliente.update(client_params)
    redirect_to clients_path
  end 

  #eliminar
  def destroy 
    @cliente.destroy
    redirect_to clients_path
  end


  private 
    def client_params
        params.require(:client).permit(:nombre, :direccion, :telefono)      
    end

    def set_client
        @cliente = Client.find(params[:id])
    end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end 
end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_producto, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]
  before_action :set_suppliers, only: [:new, :edit]

  def index 
    @productos = Product.paginate(page: params[:page], per_page: 5)
  end 

  #crear 
  def new 
    @producto = Product.new 
  end 

  def create 
    @producto = Product.create(producto_params)
    redirect_to products_path
  end 

  #editar 
  def edit 
  end 

  def update 
    @producto.update(producto_params)
    redirect_to products_path
  end 

  #eliminar
  def destroy 
    @producto.destroy
    redirect_to products_path
  end


  private 
    def producto_params
        params.require(:product).permit(:nombre, :descripcion, :marca, :modelo, :existencia, :precio, :category_id, :supplier_id)      
    end

    def set_producto
        @producto = Product.find(params[:id])
    end

    def set_categories
        @categorias = Category.all 
    end 

    def set_suppliers 
        @proveedores = Supplier.all 
    end 

end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private 

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
  
  def account_update_params 
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end 

end 

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController 
  before_action :set_supplier, only: [:edit, :update, :destroy]

  def index 
    @proveedores = Supplier.paginate(page: params[:page], per_page: 5)
  end 

  #crear 
  def new 
    @proveedor = Supplier.new 
  end 

  def create 
    @proveedor = Supplier.create(supplier_params)
    redirect_to suppliers_path
  end 

  #editar 
  def edit 
  end 

  def update 
    @proveedor.update(supplier_params)
    redirect_to suppliers_path
  end 

  #eliminar
  def destroy 
    @proveedor.destroy
    redirect_to suppliers_path
  end


  private 
    def supplier_params
        params.require(:supplier).permit(:nombre, :direccion, :telefono)      
    end

    def set_supplier
        @proveedor = Supplier.find(params[:id])
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="columns">
    <div class="column"></div>
    <div class="column my-5 has-text-centered has-background-light">
        <%= form_for @categoria do |f| %>
        <div class="field">
            <label class="label">Nombre</label>
            <div class="control">
                <%= f.text_field :nombre, autofocus: true, class: "input", autocomplete: "nombre"%>
            </div>
        </div> 

        <div class="field">
            <label class="label">Descripción</label>
            <div class="control">
                <%= f.text_area :descripcion, autofocus: true, class: "input", autocomplete: "descripcion"%>
            </div>
        </div>   
        <hr >
        <div class="field is-grouped">
            <div class="control">
                <%= f.submit(@categoria.new_record? ? "Crear" : "Actualizar", class: "button is-link")%>
            </div>
            <div class="control">
                <%= link_to "Regresar", categories_path, class: "button is-link is-light" %>
            </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/categories/edit.html.erb
<h1 class="subtitle is-3 has-text-centered"><strong>Editar categoria</strong></h1>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1 class="subtitle is-2 has-text-centered my-1">Categorias</h1>
<div class="columns">
    <div class="column"></div>
    <div class="column is-half">
        <i><%= link_to  "", new_category_path, class: "mdi mdi-plus-circle mdi-36px has-text-link" %></i>
        <table class="table is-fullwidth is-bordered">
            <thead text>
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th colspan="2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @categorias.each do |categoria|%>
                <tr>
                    <td><%= categoria.nombre %></td>
                    <td><%= categoria.descripcion %></td>
                    <td><i><%= link_to "", edit_category_path(categoria), class: "mdi mdi-tooltip-edit mdi-36px has-text-success"%></i></td>
                    <td><i><%= link_to "", category_path(categoria), method: :delete, class: "mdi mdi-delete mdi-36px has-text-danger", data: {confirm: "¿Estás seguro de eliminar la categoria: #{categoria.nombre}?"}%></i></td>
                <% end %>
                </tr>
            </tbody>
        </table>
        <%= will_paginate @categorias, renderer: BulmaPagination::Rails, :previous_label => t("anterior"), :next_label => t("siguiente"), class: 'is-rounded is-centered' %>
    </div>    
    <div class="column"></div>
</div>

app/views/categories/new.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Crear categoria</h1>
<%= render 'form', category: @category %>

app/views/clients/_form.html.erb
<div class="columns">
    <div class="column"></div>
    <div class="column my-5 has-text-centered has-background-light">
        <%= form_for @cliente do |f| %>
        <div class="field">
            <label class="label">Nombre</label>
            <div class="control">
                <%= f.text_field :nombre, autofocus: true, class: "input", autocomplete: "nombre"%>
            </div>
        </div> 

        <div class="field">
            <label class="label">Dirección</label>
            <div class="control">
                <%= f.text_field :direccion, autofocus: true, class: "input", autocomplete: "dirección"%>
            </div>
        </div>   

        <div class="field">
            <label class="label">Telefono</label>
            <div class="control">
                <%= f.text_field :telefono, autofocus: true, class: "input", autocomplete: "telefono"%>
            </div>
        </div> 

        <hr >
        <div class="field is-grouped">
            <div class="control">
                <%= f.submit(@cliente.new_record? ? "Crear" : "Actualizar", class: "button is-link")%>
            </div>
            <div class="control">
                <%= link_to "Regresar", clients_path, class: "button is-link is-light" %>
            </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/clients/edit.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Editar cliente</h1>
<%= render 'form', client: @cliente %>

app/views/clients/index.html.erb
<h1 class="subtitle is-2 has-text-centered my-1">Clientes</h1>
<div class="columns">
    <div class="column"></div>
    <div class="column is-half">
        <i><%= link_to  "", new_client_path, class: "mdi mdi-plus-circle mdi-36px has-text-link" %></i>
        <table class="table is-fullwidth is-bordered">
            <thead text>
                <tr>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>Telefono</th>
                    <th colspan="2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @clientes.each do |cliente|%>
                <tr>
                    <td><%= cliente.nombre %></td>
                    <td><%= cliente.direccion %></td>
                    <td><%= cliente.telefono %></td>
                    <td><i><%= link_to "", edit_client_path(cliente), class: "mdi mdi-tooltip-edit mdi-36px has-text-success"%></i></td>
                    <td><i><%= link_to "", client_path(cliente), method: :delete, class: "mdi mdi-delete mdi-36px has-text-danger", data: {confirm: "¿Estás seguro de eliminar al cliente: #{cliente.nombre}?"}%></i></td>
                <% end %>
                </tr>
            </tbody>
        </table>
    </div>    
    <div class="column"></div>
</div>

app/views/clients/new.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Crear cliente</h1>
<%= render 'form', client: @cliente %>

app/views/layouts/_navigation.html.erb
<nav class="navbar has-shadow is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      AUTH
    </a>

    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu" id="navMenu">
    <%= link_to "Inicio", root_path, class: "navbar-item" %>
    <% if user_signed_in? %>
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-item">Productos</a>
            <div class="navbar-dropdown">
              <%= link_to "Ver todos", products_path, class: "navbar-item" %>
              <%= link_to "Categorias", categories_path, class: "navbar-item" %>
              <%= link_to "Proveedores", suppliers_path, class: "navbar-item" %>
            </div>
          </div>
          <%= link_to "Clientes", clients_path, class: "navbar-item" %>
        </div>
        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-item"><%= current_user.name%></a>
                <div class="navbar-dropdown is-right">
                    <%= link_to 'Editar', edit_user_registration_path, class: "navbar-item"%>
                    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "navbar-item"%>
                </div>
            </div>
        </div>
    <% else %>
        <div class="navbar-end">
                <div class="buttons">
                    <%= link_to 'Registrarme', new_user_registration_path, class: "button is-primary"%>
                    <%= link_to 'Iniciar Sesión', new_user_session_path, class: "button is-primary"%>
                </div>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-body">
            <div class="container">
            <div class="columns is-centered" >
                <div class="column is-5-tablet is-4-desktop is-3-widescreen has-background-white">
                <%= yield %>
                </div>
            </div>
            </div>
        </div>
    </section>
    
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h1>Hola <%= current_user.name %> </h1>
<% end %>

app/views/products/_form.html.erb
<div class="columns">
    <div class="column"></div>
    <div class="column my-5 is-centered has-background-light">
        <%= form_for @producto do |f| %>
        <div class="field">
            <label class="label">Nombre</label>
            <div class="control">
                <%= f.text_field :nombre, autofocus: true, class: "input is-rounded", autocomplete: "nombre"%>
            </div>
        </div> 
        
        <div class="field">
            <label class="label">Descripción</label>
            <div class="control">
                <%= f.text_area :descripcion, autofocus: true, class: "input is-rounded", autocomplete: "descripcion"%>
            </div>
        </div>   

        <div class="field is-grouped">
            <div class="field">
                <label class="label">Marca</label>
                <div class="control">
                    <%= f.text_field :marca, autofocus: true, class: "input is-rounded", autocomplete: "marca"%>
                </div>
            </div> 

            <div class="field">
                <label class="label">Modelo</label>
                <div class="control">
                    <%= f.text_field :modelo, autofocus: true, class: "input is-rounded", autocomplete: "modelo"%>
                </div>
            </div>
        </div>
        
        <div class="field is-grouped">
            <div class="field">
                <label class="label">Existencia</label>
                <div class="control">
                    <%= f.number_field :existencia, autofocus: true, class: "input is-rounded", autocomplete: "existencia"%>
                </div>
            </div> 

            <div class="field">
                <label class="label">Precio</label>
                <div class="control">
                    <%= f.number_field :precio, autofocus: true, class: "input is-rounded", autocomplete: "precio"%>
                </div>
            </div> 
        </div>

        <div class="field is-grouped">
            <div>
                <label class="label">Categoria</label>
                <div class="select">
                <%= f.select :category_id,
                options_from_collection_for_select(
                @categorias, :id, :nombre, f.object.category_id), {:prompt => "Selecciona uno"}, {class: "select"}%>
                </div>
            </div>

            <div class="field">
                <label class="label">Proveedor</label>
                <div class="select">
                <%= f.select :supplier_id,
                options_from_collection_for_select(
                @proveedores, :id, :nombre, f.object.supplier_id), {:prompt => "Selecciona uno"}, {:class => "select"}%>
                </div>
            </div>
        </div>


        <!--<div class="control">
            <label class="label">Categoria</label>
            <%= collection_select(:product, :category_id, @categorias, :id, :nombre, {:prompt => 'Selecciona una categoria'}, {:class => "select" })%>
        </div>

        <div class="control">
            <label class="label">Proveedor</label>
            <%= collection_select(:product, :supplier_id, @proveedores, :id, :nombre, {:prompt => 'Selecciona un proveedor'}, {:class => "select" })%>
        </div>-->
        <hr>
        <div class="columns">
            <div class="column is-6-tablet is-offset-3-tablet">
                <div class="control">
                    <%= f.submit(@producto.new_record? ? "Crear" : "Actualizar", class: "button is-link is-fullwidth")%>
                </div><br>
                <div class="control">
                    <%= link_to "[ « regresar ]", products_path, class: "has-text-dark" %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/products/edit.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Editar producto</h1>
<%= render 'form', product: @product%>

app/views/products/index.html.erb
<h1 class="subtitle is-2 has-text-centered my-1">Productos</h1>
<div class="columns">
    <div class="column"></div>
    <div class="column is-four-fifths">
        <i><%= link_to  "", new_product_path, class: "mdi mdi-plus-circle mdi-36px has-text-link" %></i>
        <table class="table is-fullwidth is-bordered">
            <thead text>
                <tr>   
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Exitencia</th>
                    <th>Precio</th>
                    <th>Categoria</th>
                    <th>Proveedor</th>
                    <th colspan="2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @productos.each do |producto|%>
                <tr>
                    <td><%= producto.nombre %></td>
                    <td><%= producto.descripcion %></td>
                    <td><%= producto.marca %></td>
                    <td><%= producto.modelo %></td>
                    <td><%= producto.existencia %></td>
                    <td><%= producto.precio %></td>
                    <td><%= producto.category != nil ? producto.category.nombre : "No tiene categoria"%></td>
                    <td><%= producto.supplier != nil ? producto.supplier.nombre : "No tiene proveedor"%></td>
                    <td><i><%= link_to "", edit_product_path(producto), class: "mdi mdi-tooltip-edit mdi-36px has-text-success"%></i></td>        
                    <td><i><%= link_to "", product_path(producto), method: :delete, class: "mdi mdi-delete mdi-36px has-text-danger", data: {confirm: "¿Estás seguro de eliminar el producto: #{producto.nombre}?"}%></i></td>
                <% end %>
                </tr>
            </tbody>
        </table>
        <%= will_paginate @productos, renderer: BulmaPagination::Rails, :previous_label => t("anterior"), :next_label => t("siguiente"), class: 'is-rounded is-centered' %>
    </div>    
    <div class="column"></div>
</div>

app/views/products/new.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Crear producto</h1>
<%= render 'form', producto: @producto %>

app/views/suppliers/_form.html.erb
<div class="columns">
    <div class="column"></div>
    <div class="column my-5 has-text-centered has-background-light">
        <%= form_for @proveedor do |f| %>
        <div class="field">
            <label class="label">Nombre</label>
            <div class="control">
                <%= f.text_field :nombre, autofocus: true, class: "input", autocomplete: "nombre"%>
            </div>
        </div> 

        <div class="field">
            <label class="label">Dirección</label>
            <div class="control">
                <%= f.text_field :direccion, autofocus: true, class: "input", autocomplete: "dirección"%>
            </div>
        </div>   

        <div class="field">
            <label class="label">Telefono</label>
            <div class="control">
                <%= f.text_field :telefono, autofocus: true, class: "input", autocomplete: "telefono"%>
            </div>
        </div> 

        <hr >
        <div class="field is-grouped">
            <div class="control">
                <%= f.submit(@proveedor.new_record? ? "Crear" : "Actualizar", class: "button is-link")%>
            </div>
            <div class="control">
                <%= link_to "Regresar", suppliers_path, class: "button is-link is-light" %>
            </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/suppliers/edit.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Editar proveedor</h1>
<%= render 'form', supplier: @proveedor %>

app/views/suppliers/index.html.erb
<h1 class="subtitle is-2 has-text-centered my-1">Proveedores</h1>
<div class="columns">
    <div class="column"></div>
    <div class="column is-half">
        <i><%= link_to  "", new_supplier_path, class: "mdi mdi-plus-circle mdi-36px has-text-link" %></i>
        <table class="table is-fullwidth is-bordered">
            <thead text>
                <tr>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>Telefono</th>
                    <th colspan="2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @proveedores.each do |proveedor|%>
                <tr>
                    <td><%= proveedor.nombre %></td>
                    <td><%= proveedor.direccion %></td>
                    <td><%= proveedor.telefono %></td>
                    <td><i><%= link_to "", edit_supplier_path(proveedor), class: "mdi mdi-tooltip-edit mdi-36px has-text-success"%></i></td>
                    <td><i><%= link_to "", supplier_path(proveedor), method: :delete, class: "mdi mdi-delete mdi-36px has-text-danger", data: {confirm: "¿Estás seguro de eliminar al proveedor: #{proveedor.nombre}?"}%></i></td>
                <% end %>
                </tr>
            </tbody>
        </table>
        <%= will_paginate @proveedores, renderer: BulmaPagination::Rails, :previous_label => t("anterior"), :next_label => t("siguiente"), class: 'is-rounded is-centered' %>
    </div>    
    <div class="column"></div>
</div>

app/views/suppliers/new.html.erb
<h1 class="subtitle is-3 has-text-centered my-4">Crear proveedor</h1>
<%= render 'form', supplier: @proveedor %>